feat: project reorganization to make examples exercise lib usage as external so it gets bugs with lambda bundlings

diff --git a/examples/Makefile b/examples/Makefile
--- a/examples/Makefile
+++ b/examples/Makefile
@@ -1,7 +1,8 @@
 SHELL := /bin/bash
 
-build: install
+build: install prereqs
 	pnpm exec tsc --outDir dist
+	@set -x; STAGE=$${STAGE} pnpm exec cdk -o dist synth
 
 lint:
 	pnpm exec eslint ./src --ext .ts
@@ -18,8 +19,19 @@ clean:
 	rm -rf node_modules
 	rm -rf dist
 
+all-dev:
+	STAGE=dev make all
+
 all: build lint test
 
 install:
 	corepack enable
+	@# update local tar gz checksum
+	pnpm update cdk-practical-constructs
 	pnpm install --frozen-lockfile --config.dedupe-peer-dependents=false
+
+prereqs:
+	@if [ "$${STAGE}" == "" ]; then \
+		echo "ENV STAGE is required"; \
+		exit 1; \
+	fi
